name: mlproject-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - setuptools
  - pip
  - pip:
      - joblib
      - mlflow
      - wheel
