name: ML CI Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "MLProject/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
    - name: Set up job
      run: echo "Starting CI pipeline"

    - name: Checkout CI repo
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Check Env
      run: |
        echo "MLflow URI: $MLFLOW_TRACKING_URI"
        python --version

    - name: Install dependencies (Conda)
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlproject-env
        auto-activate-base: false

    - name: Run mlflow project
      shell: bash -l {0}  # penting untuk aktifkan conda
      working-directory: MLProject
      run: |
        conda activate mlproject-env
        mlflow run . \
          --entry-point main \
          -P data_path="./StudentsPerformance_cleaned.csv"

    - name: Get latest MLflow run_id
      id: get_run_id
      working-directory: MLProject
      run: |
        run_id=$(mlflow runs list --experiment-id 0 --filter-tag mlflow.runName=baseline_rf_model --output json \
                 | jq -r '.[0].run_id')
        echo "RUN_ID=$run_id" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        pip install joblib mlflow

    - name: Upload to Google Drive (placeholder)
      run: echo "Upload to Google Drive step skipped or simulated"

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: student-passed-model
        path: MLProject/artifacts/model.pkl

    - name: Build Docker Model
      working-directory: MLProject
      run: |
        mlflow models build-docker \
          -m "runs:/$RUN_ID/rf_model_passed_classifier" \
          -n ichaaulia/student-passed-classifier:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: docker tag ichaaulia/student-passed-classifier:latest ichaaulia/student-passed-classifier:latest

    - name: Push Docker Image
      run: docker push ichaaulia/student-passed-classifier:latest

    - name: Post setup
      run: echo "CI pipeline completed successfully 🎉"
