
name: ML CI Workflow
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "MLProject/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI:  ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
    - name: Checkout CI repo
      uses: actions/checkout@v3
    
    - name: Checkout preprocessing repo
      uses: actions/checkout@v3
      with:
        repository: IchaAulia12/Eksperimen_SML_Icha-aulia/preprocessing
        path: preprocessing
    - name: Setup Conda & install deps
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlproject-env
    - name: Preprocess data
      working-directory: preprocessing
      run: |
        pip install pandas    # hanya kalau belum ada
        mkdir -p processed
        python automate_Icha-aulia.py data/StudentsPerformance.csv \
              processed/StudentsPerformance_cleaned.csv
    - name: Run MLflow project
      working-directory: MLProject
      run: |
        mlflow run . \
          --entry-point main \
          -P data_path="../preprocessing/processed/StudentsPerformance_cleaned.csv"
    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: student-passed-model
        path: MLProject/artifacts/model.pkl
    - name: Build Docker via MLflow
      working-directory: MLProject
      run: |
        # Pakai MLflow helper untuk generate Dockerfile & build
        mlflow models build-docker \
          -m "runs:/$(mlflow runs list --experiment-id 0 --filter-tag mlflow.runName=baseline_rf_model --output json \
             | jq -r '.[0].run_id')/rf_model_passed_classifier" \
          -n ichaaulia/student-passed-classifier:latest

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push ichaaulia/student-passed-classifier:latest
