name: ML CI Workflow

on:
  push:
    paths:
      - "MLProject/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlproject-env

    - name: Run ML pipeline
      shell: bash -l {0}
      run: |
        cd MLProject
        python modelling.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: model
        path: MLProject/artifacts/model.pkl